### ISSUE TITLE
Compilation with GCC 5.2

### ISSUE THREAD

**Issue by wbinventor** [mit-crpg/OpenMOC#253]
I tried compiling the code on nsecluster with v5.2.0 of the GNU compilers and it failed. The compilation error trace is very long, but appears to be rooted in an issue in "Matrix.cpp." This is certainly a low priority issue since everything compiles fine with v4.8, but it would be good to fix this before >= v5.2 becomes standard.

**Comment by wbinventor** [comment]
It appears that this is not an issue after all, but was rather just an issue with the way in which I was loading modules on nsecluster.
